# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME:
  DEBEZIUM_URL:

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go install github.com/golang/mock/mockgen@v1.6.0
  - make unit-test

stages:
  - debezium

debezium:
  stage: debezium
  script:
    - export GRAFANA_TRIGGER_PAYLOAD=`cat $TRIGGER_PAYLOAD`
    - cd debezium/
    - go run .
  only:
    - trigger
