repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.43.0
    hooks:
      - id: golangci-lint
        entry: golangci-lint run -c .golangci.yml -v --fix
        stages:
          - commit

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.4
    hooks:
      - id: my-cmd-mod
        name: run unit test
        alias: go-unit-test-mod
        args: [ make, unit-test ]
