// Code generated by MockGen. DO NOT EDIT.
// Source: debezium/client.go

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDebeziumClient is a mock of DebeziumClient interface.
type MockDebeziumClient struct {
	ctrl     *gomock.Controller
	recorder *MockDebeziumClientMockRecorder
}

// MockDebeziumClientMockRecorder is the mock recorder for MockDebeziumClient.
type MockDebeziumClientMockRecorder struct {
	mock *MockDebeziumClient
}

// NewMockDebeziumClient creates a new mock instance.
func NewMockDebeziumClient(ctrl *gomock.Controller) *MockDebeziumClient {
	mock := &MockDebeziumClient{ctrl: ctrl}
	mock.recorder = &MockDebeziumClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDebeziumClient) EXPECT() *MockDebeziumClientMockRecorder {
	return m.recorder
}

// GetConnectorFailedTaskIDs mocks base method.
func (m *MockDebeziumClient) GetConnectorFailedTaskIDs(arg0 context.Context, arg1 string) (ConnectorFailedTaskIDs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectorFailedTaskIDs", arg0, arg1)
	ret0, _ := ret[0].(ConnectorFailedTaskIDs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectorFailedTaskIDs indicates an expected call of GetConnectorFailedTaskIDs.
func (mr *MockDebeziumClientMockRecorder) GetConnectorFailedTaskIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectorFailedTaskIDs", reflect.TypeOf((*MockDebeziumClient)(nil).GetConnectorFailedTaskIDs), arg0, arg1)
}

// RestartConnectorTaskByID mocks base method.
func (m *MockDebeziumClient) RestartConnectorTaskByID(arg0 context.Context, arg1 string, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartConnectorTaskByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestartConnectorTaskByID indicates an expected call of RestartConnectorTaskByID.
func (mr *MockDebeziumClientMockRecorder) RestartConnectorTaskByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartConnectorTaskByID", reflect.TypeOf((*MockDebeziumClient)(nil).RestartConnectorTaskByID), arg0, arg1, arg2)
}
